projects:
  staging:
    extensions:
      endpoints:
        default: 
          url: https://staging-graph.fitsme.kr/graphql
          headers: 
            Graphql-Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjA5MzE4MjQsImlkIjoiNWNmZjJmMDItMjQzOS00MWVhLWE5YzMtNmExOGJmNmU1YTU3Iiwic2NvcGUiOiJndWVzdCIsImlhdCI6MTU1ODMzOTgyNCwiaXNzIjoiYmxlbmRlZCJ9.c8bQx8ecIQ_r-CcXGX2FcdhSQWDhvKFpUF0ov7bJWKk"
  auth:
    extensions:
      endpoints:
        default: 
          url: https://dev-auth.fitsme.kr/graphql
          headers: 
            Graphql-Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEuMC4wIiwic2NvcGUiOiJhcHBsaWNhdGlvbiIsImlhdCI6MTU1NzkxMDM3NywiaXNzIjoiYmxlbmRlZCJ9.y5LEfaEcsluDtj_yJlMqU9hlyvkkzLsQ5w1X4_zfg2s"
  production:
    extensions:
      endpoints:
        default: https://graph.fitsme.kr/graphql
