name: Android Release

on:
  push:
    branches:
      - 'master*'

jobs:

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8 And npm install
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: npm install

      - name: Assemble app debug APK
        run: cd ./packages/app/android && bash ./gradlew assembleDebug --stacktrace

      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
