name: "build"

on:
  push:
    branches:
      - "release*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run test && npm run type-check