name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          cd packages/app && npm install
          cd packages/shared && npm install
          cd packages/web && npm install
          npm run test && npm run type-check