name: IOS Release
on:
  push:
    branches:
      - "master*"

jobs:
  ipa:
    name: Generate IPA
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Fastlane step
        uses: maierj/fastlane-action@development
        with:
          subdirectory: "packages/app"
          lane: "ios ci"
