name: IOS Release
on:
  push:
    branches:
      - "production*"

jobs:
  ipa:
    name: Generate IPA
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - name: Fastlane step
        uses: maierj/fastlane-action@v1.2.0
        with:
          subdirectory: "packages/app"
          lane: "ios ci"
        env:
          APP_DISPLAY_NAME: "RNApp"
          OUTPUT_NAME: "RNApp"
          OUTPUT_SUFFIX: ""
          PRODUCT_BUNDLE_IDENTIFIER: "kr.rnapp.apptest"
          XCODE_TEAM_ID: "787Q6972XA"
          XCODE_SCHEME: "RNApp"
          XCODE_PROJECT_NAME: "RNApp"
          XCODE_CODE_SIGN_ID: "Apple Distribution: Junhui Kim (787Q6972XA)"
          XCODE_PROVISIONING_PROFILE_NAME: "191f3fe5-d9ee-4e6b-bc6e-e7fe2bfe5b42.kr.rnapp.apptest"
          XCODE_PROVISIONING_PROFILE_UUID: "191f3fe5-d9ee-4e6b-bc6e-e7fe2bfe5b42"
          FIREBASE_TOKEN: "1//0eoKcGGVW69GBCgYIARAAGA4SNwF-L9IrtDU_S9ZQrWvYKLjQwcjzaYUVxLNtaPOOCbW0gAkKxINs6nEjAOpOSAWnAVAF297ntCo"
