name: IOS Release
on:
  push:
    branches:
      - "master*"

jobs:
  ipa:
    name: Generate IPA
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Fastlane step
        uses: maierj/fastlane-action@v1.2.0
        with:
          subdirectory: "packages/app"
          lane: "ios ci"
